In [12]:
import torch
from tensorboardX import SummaryWriter

writer = SummaryWriter(log_dir='./logs')
x = torch.FloatTensor([300])
y = torch.FloatTensor([500])

for epoch in range(100):
    x /= 1.5
    y /= 1.5
    loss = y - x
    print(loss)
    writer.add_histogram('zz/x', x, epoch)
    writer.add_histogram('zz/y', y, epoch)
    writer.add_scalar('data/x', x, epoch)
    writer.add_scalar('data/y', y, epoch)
    writer.add_scalar('data./loss', loss, epoch)
    writer.add_scalars('data/scalar_group', {'x': x,
                                             'y': y,
                                             'loss': loss}, epoch)
    writer.add_text('zz/text', 'zz: this is epoch ' + str(epoch), epoch)

# export scalar data to JSON for external processing
writer.export_scalars_to_json("./test.json")
writer.close()

tensor([133.3333])
tensor([88.8889])
tensor([59.2593])
tensor([39.5062])
tensor([26.3374])
tensor([17.5583])
tensor([11.7055])
tensor([7.8037])
tensor([5.2025])
tensor([3.4683])
tensor([2.3122])
tensor([1.5415])
tensor([1.0276])
tensor([0.6851])
tensor([0.4567])
tensor([0.3045])
tensor([0.2030])
tensor([0.1353])
tensor([0.0902])
tensor([0.0601])
tensor([0.0401])
tensor([0.0267])
tensor([0.0178])
tensor([0.0119])
tensor([0.0079])
tensor([0.0053])
tensor([0.0035])
tensor([0.0023])
tensor([0.0016])
tensor([0.0010])
tensor([0.0007])
tensor([0.0005])
tensor([0.0003])
tensor([0.0002])
tensor([0.0001])
tensor([9.1568e-05])
tensor([6.1045e-05])
tensor([4.0697e-05])
tensor([2.7131e-05])
tensor([1.8088e-05])
tensor([1.2058e-05])
tensor([8.0389e-06])
tensor([5.3593e-06])
tensor([3.5728e-06])
tensor([2.3819e-06])
tensor([1.5879e-06])
tensor([1.0586e-06])
tensor([7.0575e-07])
tensor([4.7050e-07])
tensor([3.1367e-07])
tensor([2.0911e-07])
tensor([1.3941e-07])
tensor([9.2938e-08])
tensor([6.1959e-08]

In [5]:
x = torch.FloatTensor([100])

In [13]:
import math

In [14]:
math.sin(2)

0.9092974268256817

In [19]:
for x in range(100):
    y = math.sin(x / 10)
    writer.add_scalar('sin2/x',x,x)
    writer.add_scalar('sin2/y',y,x)
