In [20]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

^^^^^^^

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [21]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [22]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])


创建一个随机初始化的矩阵:



In [23]:
x = torch.rand(5, 3)
print(x)


tensor([[2.7680e-01, 1.1993e-01, 2.8558e-01],
        [4.7255e-01, 1.8043e-01, 3.5800e-01],
        [4.9951e-02, 3.4413e-01, 7.8774e-01],
        [7.6343e-01, 7.6234e-05, 2.9646e-01],
        [4.8603e-01, 8.1187e-02, 5.2668e-01]])


numpy.random.randn(d0, d1, …, dn)是从标准正态分布中返回一个或多个样本值。

numpy.random.rand(d0, d1, …, dn)的随机样本位于[0, 1)中。


In [67]:
x1 = torch.randn(5,3)
print(x1)


tensor([[-0.0236,  0.3383, -1.2763],
        [ 0.7706, -0.3890,  1.2108],
        [ 1.1161, -0.4402,  0.5478],
        [ 0.4175,  0.7319, -0.2931],
        [-2.2566,  0.8338, -0.0759]])


创建一个0填充的矩阵，数据类型为long:



In [24]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [25]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [26]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1091,  0.3419, -0.7229],
        [-1.8782,  0.3555,  0.1134],
        [-0.3559,  0.7840, -0.7830],
        [ 0.6164, -0.2179, -1.7190],
        [-0.2747, -1.5039, -1.8032]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [27]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

^^^^^^^^^^

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [65]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.5770, 1.3970, 1.3461],
        [1.2015, 1.7312, 1.6921],
        [1.2430, 1.0794, 1.2750],
        [0.9743, 1.5710, 1.2747],
        [1.8895, 1.6093, 1.4023]])


加法2


In [29]:
print(torch.add(x, y))

tensor([[ 0.6669,  1.0498, -0.1834],
        [-1.4226,  0.9581,  0.1555],
        [ 0.0267,  1.1949, -0.0957],
        [ 0.7452,  0.3283, -1.0477],
        [ 0.3409, -1.2963, -0.8829]])


提供输出tensor作为参数



In [30]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6669,  1.0498, -0.1834],
        [-1.4226,  0.9581,  0.1555],
        [ 0.0267,  1.1949, -0.0957],
        [ 0.7452,  0.3283, -1.0477],
        [ 0.3409, -1.2963, -0.8829]])


替换



In [31]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6669,  1.0498, -0.1834],
        [-1.4226,  0.9581,  0.1555],
        [ 0.0267,  1.1949, -0.0957],
        [ 0.7452,  0.3283, -1.0477],
        [ 0.3409, -1.2963, -0.8829]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作

使用x[:,n]提取第n-1列

In [32]:
print(x[:, 1])


tensor([ 0.3419,  0.3555,  0.7840, -0.2179, -1.5039])


使用x[n,:]提取第n-1行


In [66]:
print(x[:, 1])

IndexError: too many indices for tensor of dimension 1

``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [33]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [50]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9288])
0.928820788860321


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

使用from_numpy自动转化



In [55]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [59]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
